YoungCha_x2/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('data.urls')),
    path('accounts/', include('accounts.urls')),
    path('auth/', include('social_django.urls'), name='social'),  # 소셜로그인

    # path('login/',loginapp.views.login, name='social_login')
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('nps/', include('nps.urls')),

]

accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name="accounts"

urlpatterns = [
    path('signup/', views.signup, name='signup'),#회원가입
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),


    path('password_change/', views.MyPasswordChangeView.as_view(), name='password_change'),

 #   path('login/url/', views.RequestLoginViaUrlView.as_view(), name='request_login_via_url'),
#    path('login/<uidb64>/<token>/', views.login_via_url, name='login_via_url'),

    path('password_change/', views.MyPasswordChangeView.as_view(), name='password_change'),


   # path('password_reset/', views.MyPasswordResetView.as_view(), name='password_reset'),
  #  path('reset/<uidb64>/<token>/', views.MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

data/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name='data'

urlpatterns = [
    path('ing/', views.data_show),
    path('result/', views.user_result, name='result'),
    # path('', views.loading, ),
    path('leaderboard/', views.leader_board, name='leader_board'),
    path('ready', views.ready, name='data_home'),
    path('', views.index, name="index"),
    path('user_history', views.user_result, name="history"),

]


#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nps/urls.py
from django.urls import path

from nps import views

app_name = 'nps'

urlpatterns = [
    path('debug', views.home, name='crawling'),
    path('', views.home2, name='nps'),
]

urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views




urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
    path('password_change/', views.MyPasswordChangeView.as_view(), name='password_change'),

    # path('login/url/', views.RequestLoginViaUrlView.as_view(), name='request_login_via_url'),
    # path('login/<uidb64>/<token>/', views.login_via_url, name='login_via_url'),
    # path('password_reset/', views.MyPasswordResetView.as_view(), name='password_reset'),
    # path('reset/<uidb64>/<token>/', views.MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

YoungCha_x2/templates/layout.html
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>영차영차</title>
    <link href="https://fonts.googleapis.com/css?family=Contrail+One&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" rel="stylesheet">
    <script crossorigin="anonymous"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Anton&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Advent+Pro|Orbitron&display=swap" rel="stylesheet">
    <script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Black+Han+Sans|Do+Hyeon|Noto+Sans+KR&display=swap"
          rel="stylesheet">


    <meta property='og:title' content='YCYC trading game'/>
    <meta property='og:type' content='website'/>
    <meta property='og:url' content='https://kiljaeeun.pythonanywhere.com'/>
    <meta property='og:description' content='play YCYC and earn money!'/>
    <meta property='og:image'
          content='https://postfiles.pstatic.net/MjAxOTA4MjFfMjQy/MDAxNTY2Mzg4ODU4OTUw.ljZK6MXLBBSXAXpWoqWWel1Gy5PHBqdm1iLN2Y9TEEcg.mwgBsCBsS0lE6ojBWZAQlzTNiZsKZuUN95gw9eOg7RMg.PNG.sting7675/20190821_205912.png?type=w773'/>
</head>
<body>
{#네비 YCYC 트레이딩 오늘하루 리더보드 현재 자산 계정이름 로그아웃#}

{#modal1-개미란?#}
<div class="modal fade" id="ant_ModalScrollable" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header bg-light">
                <h5 class="modal-title" id="exampleModalScrollableTitle">영차영차</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                이 개미는 노란색입니다. 모든 개미투자자들의 희망이죠.<br>
                이 땅 위의 모든 개미들을 응원합니다!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">오늘 하루도 힘내요</button>
            </div>
        </div>
    </div>
</div>
{#modal2-영차영차란?#}
<div class="modal fade" id="ycyc_ModalScrollable" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header bg-light">
                <h5 class="modal-title" id="exampleModalScrollableTitle">영어로 영차영차가 뭘까요? </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                바로 YCYC입니다. <br>
                그러나 주식을 사놓고 영차영차만 외치면 안 돼요! <br>
                꼼꼼한 종목 분석과 발빠른 뉴스 확인, <br> 그리고 굳건한 멘탈이 필수죠.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">건승을 빕니다</button>
            </div>
        </div>
    </div>
</div>

{#네비 설명#}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div id="navbar-brand">
        <a class="navbar-brand" href="#" data-toggle="modal" data-target="#ant_ModalScrollable">
            <img src="{% static "data/ant472.gif" %}" style="width: 90px; height: 60px">
        </a>
        <a class="navbar-brand" href="#" data-toggle="modal" data-target="#ycyc_ModalScrollable">
            YCYC
        </a>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarRight"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarRight">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url "data:data_home" %}">트레이딩</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url "data:leader_board" %}">리더보드</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "nps:nps" %}">국민연금</a>
            </li>
        </ul>
        <ul class="navbar-nav">

            {% if user.is_authenticated %}
                {% if user_wallet %}
                    <a class="nav-link" href="{% url "accounts:profile" %}"><i
                            class="fas fa-money-bill-wave"></i> {{ user_wallet }}원</a>
                {% endif %}

                <a class="nav-link" href='{% url "accounts:profile" %}'>{{ user }}</a>

            {% else %}

                <li class="nav-item">
                    <a class="opener2 nav-link " href="{% url 'accounts:login' %}?next={{ request.path }}">로그인</a>
                </li>
                <a href="{% url "social:begin" "google-oauth2" %}"><i class="fab fa-google-plus-square"
                                                                      style="color: white; width: 44px; height: 44px; margin: 0px 5px;"></i></a>
                <a href="{% url "social:begin" "facebook" %}"><i class="fab fa-facebook-square"
                                                                 style="color: white; width: 44px; height: 44px; margin: 0px 5px;"></i></a>

            {% endif %}

        </ul>
    </div>
</nav>

{% block content %}

{% endblock %}
</body>
</html>