YoungCha_x2/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('data.urls')),
    path('accounts/', include('accounts.urls')),
    path('auth/', include('social_django.urls'), name='social'),  # 소셜로그인

    # path('login/',loginapp.views.login, name='social_login')
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('nps/', include('nps.urls')),

]

accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name="accounts"

urlpatterns = [
    path('signup/', views.signup, name='signup'),#회원가입
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),


    path('password_change/', views.MyPasswordChangeView.as_view(), name='password_change'),

 #   path('login/url/', views.RequestLoginViaUrlView.as_view(), name='request_login_via_url'),
#    path('login/<uidb64>/<token>/', views.login_via_url, name='login_via_url'),

    path('password_change/', views.MyPasswordChangeView.as_view(), name='password_change'),


   # path('password_reset/', views.MyPasswordResetView.as_view(), name='password_reset'),
  #  path('reset/<uidb64>/<token>/', views.MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views




urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
    path('password_change/', views.MyPasswordChangeView.as_view(), name='password_change'),

    # path('login/url/', views.RequestLoginViaUrlView.as_view(), name='request_login_via_url'),
    # path('login/<uidb64>/<token>/', views.login_via_url, name='login_via_url'),
    # path('password_reset/', views.MyPasswordResetView.as_view(), name='password_reset'),
    # path('reset/<uidb64>/<token>/', views.MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

accounts/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import UserManager as AuthUserManager
from django.contrib.auth.signals import user_logged_in
from django.core.mail import send_mail
from django.db.models.signals import post_save
from django.db import models


class UserManager(AuthUserManager):
    def create_superuser(self, username, email, password, **extra_fields):
        return super().create_superuser(username, email, password, **extra_fields)


class User(AbstractUser):
    objects = UserManager()


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=30, blank=True)
    score = models.CharField(default='10000000', max_length=30)
    wallet = models.IntegerField(default=10000000)


class UserHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    stock_name = models.CharField(max_length=30, default='0')
    rate_of_return = models.CharField(max_length=10, default='0')
    total_assets = models.CharField(max_length=100,  default='0')
    amount_of_asset_change = models.CharField(max_length=100,  default='0')
    trade_numbers = models.CharField(max_length=100,  default='0')
    john_bur_term = models.CharField(max_length=10, default='0')
    game_date = models.DateTimeField(auto_now_add=True)


# def on_post_save_for_user(sender, **kwargs):
#     if kwargs['created']:
#         # 가입시기
#         user = kwargs['instance']
#
#         # 환영 이메일 보내기
#         send_mail(
#             '환영합니다.',
#             'Here is the message.',
#             'me@askcompany.kr',
#             [user.email],
#             fail_silently=False,
#         )
# post_save.connect(on_post_save_for_user, sender=settings.AUTH_USER_MODEL)


class UserSession(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, editable=False)
    session_key = models.CharField(max_length=40, editable=False)
    # created_at = models.DateTimeField(auto_now_add=True)


def on_user_logged_in(sender, request, user, **kwargs):
    user.is_user_logged_in = True


user_logged_in.connect(on_user_logged_in)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import validate_email
from .models import User, Profile


class SignupForm(UserCreationForm):
    name= forms.CharField(max_length=30,required=False)#꼭 필요는 아님
    score = forms.CharField(max_length=600,required=False)

    def __init__(self, *args, **kwargs):
         super().__init__(*args, **kwargs)
         self.fields['username'].validators = [validate_email]
         self.fields['username'].help_text = 'Enter Email Format.'
         self.fields['username'].label = 'Email'


    def save(self):
        user = super().save(commit=False)
        user.email = user.username
        user.save()

        name = self.cleaned_data.get('name', None)
        score = self.cleaned_data.get('score', None)

        Profile.objects.create(user=user, name=name, score=score,)

        return user

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('name', 'score')


    '''
    def clean_username(self):
        value = self.cleaned_data.get('username')
        if value:
            valusr_idate_email(value)
        return value
    '''


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['name','score']

accounts/views.py
from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import redirect, render, resolve_url, reverse
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from .forms import SignupForm, ProfileForm
from .models import Profile, UserHistory, User
import json
import random
# 회원가입


class SignupView(CreateView):
    model = User
    form_class = SignupForm
    template_name = 'accounts/signup.html'

    def get_success_url(self):
        next_url = self.request.GET.get('next') or 'profile'
        return resolve_url(next_url)

    def form_valid(self, form):
        user = form.save()
        auth_login(self.request, user,backend='django.contrib.auth.backends.ModelBackend')
        return redirect(self.get_success_url())


signup = SignupView.as_view()


@login_required
def profile(request):
    user_instance = User.objects.filter(id=request.user.id)[0]
    print(user_instance)
    user_history = UserHistory.objects.filter(user_id=user_instance.id)
    try:
        user_profile = Profile.objects.filter(user_id=user_instance.id)[0]
    except Exception:
        print(type(user_instance.first_name))
        print(type(user_instance.last_name))
        user_profile = Profile.objects.create(name=user_instance.first_name+user_instance.last_name, user_id=user_instance.id, wallet=10000000)
    wallet_3 = format(user_profile.wallet, ",")

    return render(request, 'accounts/profile.html', {'user_history': user_history, 'user_profile': user_profile, "user_wallet": wallet_3})


class MyPasswordChangeView(PasswordChangeView):
    success_url = reverse_lazy('data:history')
    template_name = 'accounts/password_change_form.html'

    def form_valid(self, form):
        messages.info(self.request, '암호 변경을 완료했습니다.')
        return super().form_valid(form)

#
# def user(request):
#     print('user함수')
    # user_check = User.objects.filter(id=request.user.id)
    # if not user_check:
    #     return redirect("data:data_home")
    # if not ("@" in request.user.username):
    #     user_instance_check = Profile.objects.filter(user_id=user_check[0].id)
    #     if not user_instance_check:
    #         Profile.objects.create(name=user_check[0].last_name+user_check[0].first_name, user_id=user_check[0].id, wallet=10000000)
    #         return redirect("data:data_home")
    #     else:
    #         return redirect("data:data_home")
    # return redirect("data:data_home")

# else:
#         return redirect("data:data_home")

    # if request.method == 'POST':
    #     user_result = request.POST.get("abc")
    #
    #     user_result = json.loads(user_result)
    #
    #     user_history = UserHistory.objects.all()
    #
    #     if len(user_history):
    #         latest_score = user_history[len(user_history) - 1].total_assets
    #     else:
    #         #유저 히스토리가 없을 경우 유효성 검사를 적당히 함
    #         latest_score = 999999999999
    #     user_result = request.POST.get("abc")
    #     user_result = json.loads(user_result)
    #     if user_result['total_return'] != int(float(latest_score)):
    #         try:
    #             user_instance = User.objects.filter(id=request.user.id)[0]
    #             profile_instance = Profile.objects.filter(user_id=request.user.id)[0]
    #         except IndexError:
    #             return redirect(reverse('data:data_home'))
    #
    #         profile_instance.wallet += int(user_result['total_return'])
    #
    #         profile_instance.save()
    #
    #         if user_result['delta_return'] != '0':
    #             UserHistory.objects.create(
    #                 user=user_instance,
    #                 stock_name=user_result["name"], # 0 = name
    #                 rate_of_return=user_result['total_yield'], # 1 = totalT_yield
    #                 total_assets=user_result["total_return"], # 2 = total_return
    #                 amount_of_asset_change=user_result['delta_return'], # 3 = delta_return
    #                 trade_numbers=user_result['trading_numbers'], # 4 = trading_numbers
    #                 john_bur_term=sum(list(map(float, user_result['jonber_periods']))), # 5 = jonber_periods
    #             )
    #             user_result['jonber_periods'] = [sum(list(map(float, user_result['jonber_periods'])))]
    #
    #
    #         else:
    #             UserHistory.objects.create(
    #                 user=user_instance,
    #                 stock_name=user_result[0],
    #                 rate_of_return=0,
    #                 total_assets=user_result['total_return'],
    #                 amount_of_asset_change=0,
    #                 trade_numbers=0,
    #                 john_bur_term=0,
    #             )
    #             user_result['jonber_periods'] = ['0']
    #
    #         try:
    #             user_instance = User.objects.filter(id=request.user.id)[0]
    #
    #         except IndexError:
    #             return redirect(reverse('data:data_home'))
    #
    #         user_history = UserHistory.objects.filter(user_id=user_instance.id)
    #         user = Profile.objects.filter(user_id=request.user.id)[0]
    #         wallet_3 = format(user.wallet, ",")
    #
    #         return render(request, "accounts/profile.html", {'user_history': user_history, 'user_profile': profile_instance, 'user_wallet': wallet_3})
    #
    #     else:
    #         user_instance = User.objects.filter(id=request.user.id)[0]
    #         user_history = UserHistory.objects.filter(user_id=user_instance.id)
    #         user = Profile.objects.filter(user_id=request.user.id)[0]
    #
    #         return render(request, 'accounts/profile.html', {'user_history': user_history, 'user_wallet': user.wallet})

accounts/templates/accounts/layout.html
{% extends "layout.html" %}

accounts/templates/accounts/login.html
{% extends "accounts/layout.html" %}

{% block content %}

    <style>
        .google, .facebook {
            color: white;
        }

    .bar{
        display : flex;
        justify-content: center;
        margin-bottom : 5px;

    }
    .signup{
        display: flex;
        justify-content: center;
    }
    button{
        width : 230.24px;
    }

    </style>

    <div class="container shadow p-3 mb-5 bg-white rounded">
        <h2>로그인</h2>
        <hr>
        <form action="" method="post">
            {% csrf_token %}
            <div style="display: flex; justify-content: center">
                <div class="col-12">

                    <div class="col-md-8" style="margin: 0 auto;">
                        <label for="username">Email(ID)</label>
                        <input type="text" name='username' class="form-control is-valid" id="id_username"
                               placeholder="Email"
                               required>
                        <div class="valid-feedback">
                            이메일을 입력하세요!

                        </div>
                    </div>


                    <div class="col-md-8" style="margin: 0 auto;">
                        <label for="password">password</label>
                        <input type="password" name="password" class="form-control is-valid" id="id_password1"
                               placeholder="password" required>
                        <div class="valid-feedback">
                            최소 8문자 이상의 비밀번호를 입력하세요!
                            {{ form.errors.password1 }}
                        </div>
                    </div>
                    <br>
                    <br>
                    <br>


                    <div class="col-md-8" style="margin:0 auto">
                        <div class="bar">
                            <button class="btn btn-primary" type="submit">로그인</button>
                        </div>

                        <div class="bar">
                            <button class="btn btn-primary"><a class="google"
                                                               href="{% url "social:begin" "google-oauth2" %}">
                                <i
                                        class="fab fa-google"></i> 구글아이디로 로그인하기.</a></button>
                        </div>
                        <div class="bar">
                            <button class="btn btn-primary"><a class="facebook"
                                                               href="{% url "social:begin" "facebook" %}"><i
                                    class="fab fa-facebook-f"></i> 페북아이디로 로그인하기.</a></button>
                        </div>
                    </div>

                </div>
            </div>
            <hr>
            <div class="col-md-12">


                <a  class="signup" href="{% url 'accounts:signup' %}?next={{ request.path }}">
                    <button type="button" class="btn btn-outline-info">

                        회원가입
                    </button>
                </a>
            </div>
        </form>

    </div>



{% endblock %}

accounts/templates/accounts/password_change_done.html
{% extends "accounts/layout.html" %}

{% block content %}
    <h2>암호 변경 완료</h2>

    암호 변경을 완료했습니다.
{% endblock %}

accounts/templates/accounts/password_change_form.html
{% extends "accounts/layout.html" %}

{% block content %}


<div class="container shadow p-3 mb-5 bg-white rounded">
    <h2>암호 변경</h2>
    <hr>
    <div class="container">



    <form action="" method="post" style="margin: 0 auto">    {% csrf_token %}




             <div class="col-md-8">
                <label for="password">예전비밀번호</label>
                <input type="password" name='old_password' class="form-control is-valid"  placeholder="old_password"
                        required>

                </div>
             <div class="col-md-8">
                <label for="newpassword1">new_password1</label>
                <input type="password" name='new_password1' class="form-control is-valid"  placeholder="newpassword"
                        required>

                </div>
                             <div class="col-md-8">
                <label for="new_password2">password 확인</label>
                <input type="password" name='new_password2' class="form-control is-valid"  placeholder="newpassword_check"
                        required>



</div>
<div class="col-md-8">
        <button class="btn btn-primary" type="submit">Submit form</button> </div>
</form></div>

</div>




{% endblock %}

accounts/templates/accounts/profile.html
{% extends "accounts/layout.html" %}

{% block content %}
{% load staticfiles %}
<style>
ul{
   list-style:none;
   padding-left:5px;
   }
table{
text-align: center;
}

img{
    margin: 0 auto;
}



.left{
text-align:left;
}
</style>
<body>

    <div class="container  shadow p-3 mb-5 bg-white rounded" style="margin-top: 30px">
    <div class="row ">

        <div class="col-xsm-9 col-sm-9 col-md-3 left">
        <div class="container  ">
            <div class="row">
                <img src="{% static "data/user.gif" %}" style="margin-bottom: 30px;    width: 200px;  height: 230px; border: 0px;">
            </div>
            <div class="row" >
            {% if user.profile.name%}
             <ul>  <li> <h3 style="margin-bottom:10px">{{ user.profile.name|default:"&dash;" }}'s Profile</h3></li>
             {%endif%}
<hr>


              <li>  <strong><i class="far fa-envelope-open"></i>

</strong>
                 {{ user.username}}
             </li>
             <li>  <i class="fas fa-wallet"></i>


</strong>  {{ user_profile.wallet}}원

             </li>
             <li>
                <strong>
                <i class="far fa-user"></i>

                </strong>{{ user.profile.name |default:"알수없음"}}
                </li><li>
               <strong><i class="fas fa-door-open"></i></strong></li><li>{{ user.date_joined }}</li>

            <hr>
    <li>        <a style="margin-right: 20px; "href="{% url 'accounts:logout' %}?next={{ request.path }}"
                   onclick="return confirm('Are you sure?');">로그아웃</a>
           <a href="{% url "accounts:password_change" %}">암호 변경하기</a>

    </li>
            </div>
         </div>
      </div>
        <div class="col-xsm-9 col-sm-9  col-md-9">
            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">플레이 일시</th>
                    <th scope="col">기업명</th>
                    <th scope="col">수익률</th>
                    <th scope="col">기말자산</th>
                    <th scope="col">증감액</th>
                </tr>
                {% for user_h in user_history %}
                    <tr>

                        {#    수익 : {{ user_h.rate_of_return }}#}
                        <th scope="col">{{ user_h.game_date }}</th>
                        <th scope="col">{{ user_h.stock_name }}</th>
                        <th scope="col">{{ user_h.rate_of_return }}(%)</th>
                        <th scope="col">{{ user_h.total_assets }}</th>
                        <th scope="col">{{ user_h.amount_of_asset_change }}</th>


                    </tr>
                {% endfor %}


                </thead>
                <tbody>


                </tbody>
            </table>
            {% if not user_history %}
                {{ user_profile.profile.score|default:"전적이 없습니다." }}
            {% endif %}
        </div>
    </div>

    <br>




</body>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "accounts/layout.html" %}

{% block content %}
    {% load staticfiles %}
    <style>

        .left {
            float: left;
            text-align: center;
            padding: 50px;


        }

        .image .image1 {
            width: 100%;
        }

        .right {
            float: left;

            padding: 40px;
        }
        .image{
            width:100%;
        }
    </style>
    <link href="https://fonts.googleapis.com/css?family=Cinzel|Handlee|Libre+Baskerville|Lobster|Merienda+One|Nunito|Tangerine&display=swap"
          rel="stylesheet">


    <div class="wrapper">

        <div class="left col-md-6">
            {% load staticfiles %}

            <div class="image">
            <img src="{% static "accounts/loading.gif" %}" alt="??" class="image1">

            </div>

        </div>
        <div class="right col-md-6">


            <form action="" method="post">    {% csrf_token %}


                <div class="col-md-8">
                    <label for="name">Username</label>
                    <input type="text" name='name' class="form-control is-valid" id="id_name" placeholder="Username"
                           required>

                    <div class="valid-feedback">
                        이름을 입력하세요

                    </div>
                </div>


                <div class="col-md-8">
                    <label for="username">Email(ID)</label>
                    <input type="text" name='username' class="form-control is-valid" id="id_username"
                           placeholder="Email"
                           required>
                    {#                 이것은 {{ form.username }}과 같아#}
                    <div class="valid-feedback">
                        이메일을 입력하세요!
                        {{ form.errors.username }}
                        {#                    현재 위에 메시지는 작동이 안됩니다..errors.username이것들 다 안되고 있어#}

                    </div>
                </div>


                <div class="col-md-8">
                    <label for="password1">Password</label>
                    <input type="password" name="password1" class="form-control is-valid" id="id_password1"
                           placeholder="password" required>
                    <div class="valid-feedback">
                        최소 8문자 이상의 비밀번호를 입력하세요!
                        {{ form.errors.password1 }}
                    </div>
                </div>
                <div class="col-md-8">
                    <label for="password2">Password check</label>
                    <input type="password" name="password2" class="form-control is-valid" id="id_password2"
                           placeholder="password_check"
                           required>
                    <div class="valid-feedback">
                        비밀번호를 한 번더 입력해주세요!
                        {{ form.errors.password2 }}
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="form-group form-check">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1" required>
                        <label class="form-check-label" for="exampleCheck1">개인정보 사용에 동의합니다</label>
                    </div>
                </div>
                <div class="col-md-8">
                    <button class="btn btn-primary" type="submit">Submit form</button>
                </div>
            </form>
        </div>


    </div>



{% endblock %}